### ISSUE TITLE
Improvement to AES-GCM

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/js-encryptedfs#12]
https://news.ycombinator.com/item?id=19693434

**Comment by CMCDragonkai** [comment]
Hey @robert-cronin I think you mentioned this is not necessary in our previous review. Can you justify it here, and close this issue?

**Comment by robert-cronin** [comment]
Yeah so `AES-GCM-SIV` is primarily used to prevent the same init vector from encrypting the same data more than once, i.e. a nonce being reused. This is a concern in encryption as an attacker can observe repeat encryptions with the same init vector and message.
I believe this to be redundant in EFS because the init vector we use for chunk level encryption is randomised _every time_ a chunk is encrypted so reusing of a nonce doesn't occur.
